---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by njcx.
--- DateTime: 2021-01-18 13:31
---


local _M ={
}

_M.prod ={

    response_log_dir = "/data/log/nginx/hack/",
    error_log_path  = '/tmp/',
    access_log_path = '/data/log/nginx/hack/',
    info_log_path = '/tmp/',
}

_M.dev ={

    response_log_dir = "/Users/njcx/openresty-1.13.6.2-bin/nginx/logs/",
    error_log_path  = '/Users/njcx/openresty-1.13.6.2-bin/nginx/logs/',
    access_log_path = '/Users/njcx/openresty-1.13.6.2-bin/nginx/logs/',
    info_log_path = '/Users/njcx/openresty-1.13.6.2-bin/nginx/logs/',

}

_M.demo={
    response_log_dir = "/data/log/nginx/hack/",
    error_log_path  = '/tmp/',
    access_log_path = '/data/log/nginx/hack/',
    info_log_path = '/tmp/',
}


function _M.config_init()

    --- if env == 'prod'
    --- info should be 'false'

    env = 'prod'                    --string- prod,dev,demo
    info = true                    --boolean- true or false
    ip_for_both = true              --boolean- true or false

    --- 如果只用高防转发，请置  ip_for_both = false，可看到WAF被绕过记录
    --- 如果高防转发和流量直达混用， 请置  ip_for_both = true，WAF被绕过检测功能将失效

end

return _M